### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alphanumericaltycoon** [milan102/Auto-eBay-Feedback#2]
Would be great if you could make it so that it leaves feedback for buyers who have already left positive feedback and ignores those who have left neutral or negative.

**Comment by milanify** [comment]
With the current implementation it would be tough to do so without calling an eBay API or making the app more complicated in general. The way I do it is manually leave negative/neutral feedback for those buyers then let the add-on automatically do the positive for everyone else

**Comment by alphanumericaltycoon** [comment]
Hi, as a business seller you can't leave buyers with negative or neutral feedback only positive.

**Comment by milanify** [comment]
Oh interesting. I'm a small time seller so I would've never had known. Right now this will remain a simple just dummy feedback add-on that leaves all positive, I'm actually surprised it has been working this entire time, 4 years going strong.
